### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by maebug** [zweishar/twitteroauth#2]
## Code Review
`twitteroauth/templates/twitteroauth-content.html.twig` 
- List `created_at` as an available variable.

`twitteroauth/src/TweetFetcher.php`
- If being nit-picky about alphabetical order, then `use Drupal\Core\Config\ConfigFactory;` should come before `use Drupal\Core\Logger\LoggerChannelFactory;`
- On line 205 should the error message be configurable by site admins?

`twitteroauth/twitteroauth.module`
- The `#_entity` array key seems kind of weird. Is it possible to just use `#entity`?

I'm also curious if it might be possible and/or worthwhile to add a wrapper template. As-is the Twitter API results are displayed individually in `twitteroauth-content.html.twig` instead of looping through the results. This is really only a problem if a themer is trying add a wrapper element, say for grid markup or something similar.

**Comment by zweishar** [comment]
> The #_entity array key seems kind of weird. Is it possible to just use #entity

I agree that it's kinda weird, but I did not use `#entity` because I've seen that being passed around in render arrays before. I'm trying to avoid conflict with other functions, potentially overwriting whatever they put in `#entity`, or perhaps avoiding a case where another module overrides what I put in `#entity`.

I don't have a strong opinion on the wrapper template. I removed it with the idea that a themer could use the block template as the wrapper if they needed it, but that would also require them to know how to write template suggestions, so maybe that's too much to ask? I'm happy to add one in if you think it's helpful.

I'll make the other suggested changes, they are all quite sensible.

**Comment by maebug** [comment]
Right. That makes sense about `#_entity`. It's not ideal but hard to think of a better variable name to use.

Personally I think the wrapper template will make the module more accessible to new developers and make it easier to just jump right in and theme. Another use case/situation would be when a developer wants to use some default block styling. Having a wrapper template would minimize repeated code. That being said, I don't think it's absolutely _critical_ to have the wrapper template but I would certainly vote for adding it.
